server:
  port: 0

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/inventory-service
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service
  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka