server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/inventory-service
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update